<?php
/** Full editable block-editor demo data. */
if (!defined('ABSPATH')) { exit; }
function stillform_demo_specs() {
 $note='<p><em>Fictional project for demonstration. Licensed photography does not represent authorship by Stillform.</em></p>';
 return [
 'media'=>[
 'courtyard-house.jpg'=>['Courtyard House','Sunlit concrete courtyard and reflecting pool','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c'],
 'threshold-house.jpg'=>['House of Thresholds','Warm minimal interior opening to a garden','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3'],
 'ochre-rooms.jpg'=>['Ochre Rooms','Layered neutral living room with sculptural furniture','https://images.unsplash.com/photo-1600607688969-a5bfcd646154'],
 'pavilion.jpg'=>['Tidal Pavilion','Contemporary pavilion framed by open landscape','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d'],
 'material-study.jpg'=>['Material study','Quiet room in timber and soft mineral finishes','https://images.unsplash.com/photo-1600210492486-724fe5c67fb0'],
 'stair-light.jpg'=>['Stair and light','Sculptural stair washed with daylight','https://images.unsplash.com/photo-1600607688960-e095ff83135c'],
 'stone-detail.jpg'=>['Stone detail','Natural stone and timber interior detail','https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea'],
 'studio-table.jpg'=>['Studio table','Architectural studio table and material samples','https://images.unsplash.com/photo-1600566752355-35792bedcfea']],
 'pages'=>[
 'home'=>['Home','<!-- wp:paragraph --><p>Stillform is a fictional demonstration practice. All projects and editorial texts are demo material.</p><!-- /wp:paragraph -->','A fictional architecture studio demonstration.','','courtyard-house.jpg'],
 'studio'=>['Studio','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">Stillform is an independent, fictional practice working across architecture, interiors and objects. We make calm, tactile places that support ordinary life.</p><!-- /wp:paragraph --><!-- wp:columns {"align":"wide"} --><div class="wp-block-columns alignwide"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Attention before form</h3><!-- /wp:heading --><p>We begin by recording how a place is used: morning light, daily routes and moments of pause.</p></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Material with purpose</h3><!-- /wp:heading --><p>Stone, timber, lime and metal are chosen for how they age, feel and can be repaired.</p></div><!-- /wp:column --></div><!-- /wp:columns --><!-- wp:quote --><blockquote class="wp-block-quote"><p>The work should feel inevitable, but never anonymous.</p></blockquote><!-- /wp:quote --><!-- wp:heading --><h2 class="wp-block-heading">A small studio, built around dialogue.</h2><!-- /wp:heading --><p>Our fictional team brings together architecture, interior design, furniture and landscape thinking. We keep decisions direct and the project’s central idea visible from first sketch to final fitting.</p>','A small fictional practice built around attention, material and dialogue.','templates/studio.php','studio-table.jpg'],
 'projects'=>['Projects','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">Four fictional studies in climate, material and domestic ritual. Photography is licensed demonstration imagery and does not depict work authored by Stillform.</p><!-- /wp:paragraph -->','Selected fictional architectural studies.','templates/projects.php',''],
 'journal'=>['Journal','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">Notes from a fictional practice on material, proportion and the atmosphere of useful rooms.</p><!-- /wp:paragraph -->','Notes on material, proportion and atmosphere.','templates/journal.php',''],
 'contact'=>['Contact','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">For fictional commissions, collaborations and press enquiries, begin with an email describing the place, ambition and likely timescale.</p><!-- /wp:paragraph --><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">New work</h3><!-- /wp:heading --><p>The address displayed by the theme is configurable. No contact form pretends to submit data.</p><!-- wp:heading {"level":3} --><h3 class="wp-block-heading">Studio visits</h3><!-- /wp:heading --><p>Demo studio · London / Remote<br>Visits by appointment only.</p>','Contact the fictional Stillform studio.','templates/contact.php','stone-detail.jpg']],
 'projects'=>[
 ['courtyard-house','Courtyard House','A low, inward-looking home organised around water, shade and the movement of the sun.','Residential','2026','Completed','courtyard-house.jpg','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">This fictional courtyard house turns away from the street and opens to planted rooms.</p><!-- /wp:paragraph --><h2 class="wp-block-heading">A room made from weather</h2><p>Four simple wings gather around a shallow pool. Deep reveals temper summer sun while winter light reaches lime-plastered walls.</p>'.$note],
 ['house-of-thresholds','House of Thresholds','A compact renovation using deep openings and built-in furniture to give a modest plan unexpected depth.','Residential','2025','Completed','threshold-house.jpg','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">A fictional renovation where the space between rooms becomes as important as the rooms.</p><!-- /wp:paragraph --><h2 class="wp-block-heading">Living in the thickness</h2><p>Oak-lined thresholds hold shelves, seats and sliding screens, allowing the house to change with the season.</p>'.$note],
 ['ochre-rooms','Ochre Rooms','A guesthouse composed as warm, monolithic rooms around a shared table.','Hospitality','2025','Concept','ochre-rooms.jpg','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">A fictional guesthouse that asks how hospitality can feel elemental and personal.</p><!-- /wp:paragraph --><h2 class="wp-block-heading">Colour as orientation</h2><p>Pigmented plaster shifts from earth red at the public heart to chalk and clay in private rooms.</p>'.$note],
 ['tidal-pavilion','Tidal Pavilion','A seasonal room at the water’s edge, designed to weather with the changing coast.','Cultural','2024','Concept','pavilion.jpg','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">A fictional public room treating tide, wind and salt as collaborators.</p><!-- /wp:paragraph --><h2 class="wp-block-heading">A structure that can yield</h2><p>The pavilion rests on a demountable frame. Every component can be lifted by a small team and repaired with familiar tools.</p>'.$note]],
 'posts'=>[
 ['the-weight-of-a-threshold','The weight of a threshold','A threshold can slow the body, tune the light and prepare us for another kind of room.','stair-light.jpg','2026-09-18 09:00:00','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">The smallest transition in a plan can carry the emotional weight of a whole building.</p><!-- /wp:paragraph --><p>Thresholds are temporal: a shaded porch before bright interior, a low opening before a tall room. Their depth creates places to sit, store and pause.</p><p>This is fictional editorial content created for the Stillform demonstration website.</p>'],
 ['material-not-moodboard','Material is not a moodboard','Fewer materials can make a space richer when each is allowed to age and carry evidence of use.','material-study.jpg','2026-08-27 09:00:00','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">A palette becomes architecture only when materials are asked to do real work.</p><!-- /wp:paragraph --><p>We move from references to samples large enough to hold, scratch and place in changing daylight.</p><p>This is fictional editorial content created for the Stillform demonstration website.</p>'],
 ['drawing-with-daylight','Drawing with daylight','Light is a building material with a schedule. Good rooms anticipate how it moves and disappears.','stone-detail.jpg','2026-07-12 09:00:00','<!-- wp:paragraph {"fontSize":"large"} --><p class="has-large-font-size">Daylight is not simply something a window admits. It is something a room edits.</p><!-- /wp:paragraph --><p>A deep soffit cuts glare; a pale reveal catches light after the sun leaves the glass. The aim is not maximum brightness but useful contrast.</p><p>This is fictional editorial content created for the Stillform demonstration website.</p>']]];
}
